# .github/workflows/deploy.yml

name: Build and Deploy to arifabds.github.io

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install and Build
        run: |
          npm install
          npm run build
      
      - name: Deploy to Target Repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_PAGES_TOKEN }}
          
          repository-name: arifabds/arifabds.github.io
          
          branch: main 
          
          folder: out 
          
          clean: true 